"""
PDF Export functionality for research reports
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from datetime import datetime
import io

class PDFExporter:
    """Export research reports to PDF"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Create custom styles for the report"""
        
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor='#1a1a1a',
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        # Heading style
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor='#d4af37',
            spaceBefore=12,
            spaceAfter=6
        ))
        
        # Body style
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['BodyText'],
            fontSize=11,
            alignment=TA_JUSTIFY,
            spaceAfter=12
        ))
    
    def export_report(self, query: str, report_content: str) -> bytes:
        """Export research report to PDF"""
        
        # Create PDF in memory
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        
        # Build content
        story = []
        
        # Title
        title = Paragraph(f"Research Report: {query}", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.2*inch))
        
        # Metadata
        date_text = f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
        metadata = Paragraph(date_text, self.styles['Normal'])
        story.append(metadata)
        story.append(Spacer(1, 0.3*inch))
        
        # Content
        # Convert markdown-style content to PDF paragraphs
        lines = report_content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.1*inch))
                continue
            
            # Headings
            if line.startswith('# '):
                p = Paragraph(line[2:], self.styles['CustomTitle'])
                story.append(p)
            elif line.startswith('## '):
                p = Paragraph(line[3:], self.styles['CustomHeading'])
                story.append(p)
            elif line.startswith('### '):
                p = Paragraph(line[4:], self.styles['Heading3'])
                story.append(p)
            # Bullet points
            elif line.startswith('- ') or line.startswith('* '):
                p = Paragraph(f"• {line[2:]}", self.styles['CustomBody'])
                story.append(p)
            # Bold text
            elif line.startswith('**') and line.endswith('**'):
                p = Paragraph(f"<b>{line[2:-2]}</b>", self.styles['CustomBody'])
                story.append(p)
            # Regular paragraph
            else:
                p = Paragraph(line, self.styles['CustomBody'])
                story.append(p)
        
        # Footer
        story.append(Spacer(1, 0.5*inch))
        footer = Paragraph(
            "<i>Generated by DiveIn AI Research Assistant | Pace University</i>",
            self.styles['Normal']
        )
        story.append(footer)
        
        # Build PDF
        doc.build(story)
        
        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
